export const USER_ACTION_TYPES = {
    SET_CURRENT_USER: 'user/SET_CURRENT_USER',
    SET_CURRENT_MESSAGES: 'user/SET_CURRENT_MESSAGES',
    SET_ADD_MESSAGE: 'user/SET_ADD_MESSAGE',
    SET_CURRENT_LOCATION: 'user/SET_CURRENT_LOCATION',
    SET_PLAYERS_LOCATION: 'user/SET_PLAYERS_LOCATION',
    SET_LOAD_POST: 'user/SET_LOAD_POST',
    SET_UPDTE_MESSAGE : 'user/SET_UPDTE_MESSAGE',
    SET_CURRENTPLAYERS : 'user/SET_CURRENTPLAYERS',
    SET_CURRENT_PROFILE_IMG : 'user/SET_CURRENT_PROFILE_IMG',
    ADD_FOLLOW : 'user/ADD_FOLLOW',
    REMOVE_FOLLOW : 'user/REMOVE_FOLLOW',
    SET_ROUTE : 'user/SET_ROUTE',
    SetUnreadMessages : 'user/SetUnreadMessages',
    SETTHEME : 'user/SETTHEME',
    SET_CURRENT_USERNAME : 'user/SET_CURRENT_USERNAME',
    SET_CURRENT_BIO : 'user/SET_CURRENT_BIO',
    EDIT_CURRENT_MESSAGE : 'user/EDIT_CURRENT_MESSAGE'

}
